### PR TITLE
Add Atom feed

### PR DESCRIPTION
**Pull request by madewokherd**
This adds a news feed in Atom format (and fixes generated line-endings on Windows because that's where I did all my development/testing).

There are absolute references to the wine-staging domain, which I noticed you've avoided, but they are only for the <id> values which are not supposed to be interpreted as links by clients (and are not allowed to be relative). It's not important that they match the actual URL of anything in particular, just that they are unique, and including a domain you control is just one way to do that.

I wasn't sure what would be a good way to add a link to the body, so I didn't. It's just in the html head, which means for now it'll be invisible to most people.

### CODE REVIEW

**Comment by mmueller2012** [comment]
Thanks for adding atom feed support, I will add a link into the footer later :+1:

**Comment by madewokherd** [comment]
I see you've added the full content to the feed. I don't know if it makes a difference for any real clients, but you should technically use the <content> tag instead of <summary>

 in this case.

**Comment by madewokherd** [comment]
Github doesn't automatically escape less than/greater than? I meant "content" tag instead of "summary" tag.

**Comment by mmueller2012** [comment]
Fixed in 8063d94bb47d988011babb44f229010e37c49ad3, thanks for noticing.

**Pull request merged**
